# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(830, 420)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 812, 384))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.converter = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.converter.setFont(font)
        self.converter.setObjectName("converter")
        self.gridLayout.addWidget(self.converter, 4, 0, 1, 3)
        self.linkedin = QtWidgets.QLabel(self.gridLayoutWidget)
        self.linkedin.setAlignment(QtCore.Qt.AlignCenter)
        self.linkedin.setOpenExternalLinks(True)
        self.linkedin.setObjectName("linkedin")
        self.gridLayout.addWidget(self.linkedin, 8, 2, 3, 1)
        self.github = QtWidgets.QLabel(self.gridLayoutWidget)
        self.github.setAlignment(QtCore.Qt.AlignCenter)
        self.github.setOpenExternalLinks(True)
        self.github.setObjectName("github")
        self.gridLayout.addWidget(self.github, 8, 1, 3, 1)
        self.nomeArquivo = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.nomeArquivo.setObjectName("nomeArquivo")
        self.gridLayout.addWidget(self.nomeArquivo, 3, 0, 1, 3)
        self.msgSucesso = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.msgSucesso.setObjectName("msgSucesso")
        self.gridLayout.addWidget(self.msgSucesso, 5, 0, 1, 3)
        self.encerrarApp = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.encerrarApp.setObjectName("encerrarApp")
        self.gridLayout.addWidget(self.encerrarApp, 6, 0, 1, 3)
        self.textBrowser = QtWidgets.QTextBrowser(self.gridLayoutWidget)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 0, 0, 1, 3)
        self.label1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label1.setObjectName("label1")
        self.gridLayout.addWidget(self.label1, 8, 0, 3, 1)
        self.escolherDB = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.escolherDB.setFont(font)
        self.escolherDB.setObjectName("escolherDB")
        self.gridLayout.addWidget(self.escolherDB, 1, 0, 1, 3)
        self.escolherExcel = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.escolherExcel.setFont(font)
        self.escolherExcel.setObjectName("escolherExcel")
        self.gridLayout.addWidget(self.escolherExcel, 2, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.converter.setText(_translate("MainWindow", "Converter"))
        linkTemplate = '<a href={0}>{1}</a>'
        self.linkedin.setText("<a href='https://www.linkedin.com/in/renan-leite-vieira-b81a85247/'>LinkedIn</a>")
        self.github.setText("<a href='https://github.com/renanleitev'>Github</a>")
        self.encerrarApp.setText(_translate("MainWindow", "ENCERRAR PROGRAMA"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Bem-vindo ao ConversorDB. Ele permite converter arquivos em formato .db (banco de dados) para formato .xslx (Excel) e vice-versa.</p></body></html>"))
        self.label1.setText(_translate("MainWindow", "Desenvolvido por Renan Leite Vieira. Siga-me em:"))
        self.escolherDB.setText(_translate("MainWindow", "Escolher Banco de Dados (DB)"))
        self.escolherExcel.setText(_translate("MainWindow", "Escolher Planilha Excel (XSLX)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
